### ISSUE TITLE
Windows dependency dll not being loaded on few Windows machines

### ISSUE THREAD

**Issue by krishnaIndia** [maidsafe/safe_browser#101]
Operation System: Windows 10
Beaker Version: 0.4.0

Loading native libraries fail with error code 193 on few windows machines.

```
C:\Users\Az\Downloads\safe-browser-v0.4.0-win-x64\safe-browser-v0.4.0-win-x64>
[PLUGINS] Failed to load plugin beaker-plugin-safe-app Error: Dynamic Linking Error: Win32 error 193
at new DynamicLibrary (C:\Users\Az\Downloads\safe-browser-v0.4.0-win-x64\safe-browser-v0.4.0-win-x64\resources\app\node_modules\ffi\lib\dynamic_library.js:74:11)
at Object.DynamicLibrary (C:\Users\Az\Downloads\safe-browser-v0.4.0-win-x64\safe-browser-v0.4.0-win-x64\resources\app\node_modules\ffi\lib\dynamic_library.js:33:12)
at Object. (C:\Users\Az\Downloads\safe-browser-v0.4.0-win-x64\safe-browser-v0.4.0-win-x64\resources\app\node_modules\safe-app\src\native\lib.js:20:17)
at Module._compile (module.js:556:32)
at Object.Module._extensions…js (module.js:565:10)
at Module.load (module.js:473:32)
at tryModuleLoad (module.js:432:12)
at Function.Module._load (module.js:424:3)
at Module.require (module.js:483:17)
at require (internal/module.js:20:19)
Error: Dynamic Linking Error: Win32 error 193
at new DynamicLibrary (C:\Users\Az\Downloads\safe-browser-v0.4.0-win-x64\safe-browser-v0.4.0-win-x64\resources\app\node_modules\ffi\lib\dynamic_library.js:74:11)
at Object.DynamicLibrary (C:\Users\Az\Downloads\safe-browser-v0.4.0-win-x64\safe-browser-v0.4.0-win-x64\resources\app\node_modules\ffi\lib\dynamic_library.js:33:12)
at C:\Users\Az\Downloads\safe-browser-v0.4.0-win-x64\safe-browser-v0.4.0-win-x64\resources\app\node_modules\beaker-plugin-safe-authenticator\dist\api.js:193:36
at LibLoader.load (C:\Users\Az\Downloads\safe-browser-v0.4.0-win-x64\safe-browser-v0.4.0-win-x64\resources\app\node_modules\beaker-plugin-safe-authenticator\dist\api.js:187:15)
at Object.loadLibrary (C:\Users\Az\Downloads\safe-browser-v0.4.0-win-x64\safe-browser-v0.4.0-win-x64\resources\app\node_modules\beaker-plugin-safe-authenticator\dist\api.js:96:25)
at Object. (C:\Users\Az\Downloads\safe-browser-v0.4.0-win-x64\safe-browser-v0.4.0-win-x64\resources\app\node_modules\beaker-plugin-safe-authenticator\index.js:5:19)
at Module._compile (module.js:556:32)
at Object.Module._extensions…js (module.js:565:10)
at Module.load (module.js:473:32)
at tryModuleLoad (module.js:432:12)
```

**Comment by Viv-Rajkumar** [comment]
Missing [2015 Visual C++ redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=48145) could be the issue here due to the lack of an installer confirming the presence of the required dependencies and optionally installing them.

Similar resolved issue details from [the forum](https://safenetforum.org/t/maidsafe-dev-update-august-3-2017-test-18/15261/93?u=viv)

**Comment by joshuef** [comment]
@krishnaIndia @Viv-Rajkumar are you aware if this is still an issue with our installers?

**Comment by bochaco** [comment]
I'm closing this now, but please re-open it if you reckon there are still cases where this happen.
