### ISSUE TITLE
Uncought exception

### ISSUE THREAD

**Issue by Folatt** [maidsafe/safe_browser#271]
Operation System and Version: Arch Linux
SAFE Browser Version: 0.10.1 to 0.10.2
Network: Alpha 2
Description: Uncaught Exception
Steps to reproduce: Error message pops up as soon as I run it.

Uncaught Exception:
1000
    at module.exports (/home/folatt/Downloads/safe-browser-v0.10.1-linux-x64/resources/app/node_modules/@maidsafe/safe-node-app/src/native/_error.js:19:10)
    at Object.ffi.init (/home/folatt/Downloads/safe-browser-v0.10.1-linux-x64/resources/app/node_modules/@maidsafe/safe-node-app/src/native/lib.js:58:11)
    at SAFEApp (/home/folatt/Downloads/safe-browser-v0.10.1-linux-x64/resources/app/node_modules/@maidsafe/safe-node-app/src/app.js:36:9)
    at Object.initializeApp (/home/folatt/Downloads/safe-browser-v0.10.1-linux-x64/resources/app/node_modules/@maidsafe/safe-node-app/src/index.js:61:25)
    at netStateCallbackHelper (/home/folatt/Downloads/safe-browser-v0.10.1-linux-x64/resources/app/node_modules/beaker-plugin-safe-app/dist/api.js:230:11)
    at Object.module.exports.module.exports._with_async_cb_initialise [as initialise] (/home/folatt/Downloads/safe-browser-v0.10.1-linux-x64/resources/app/node_modules/beaker-plugin-safe-app/dist/api.js:391:10)
    at Promise (/home/folatt/Downloads/safe-browser-v0.10.1-linux-x64/resources/app/background-process.build.js:1631:32)
    at Promise (<anonymous>)
    at authoriseApp (/home/folatt/Downloads/safe-browser-v0.10.1-linux-x64/resources/app/background-process.build.js:1629:10)
    at dispatch.payload.Promise (/home/folatt/Downloads/safe-browser-v0.10.1-linux-x64/resources/app/background-process.build.js:1534:9)

**Comment by hunterlester** [comment]
@Folatt I'm wondering if this is related to https://github.com/maidsafe/safe_examples/issues/389, where you need to check if `NODE_ENV=dev` is set system-wide.
