### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Folatt** [maidsafe/safe_browser#61]
Operation System: Arch
Beaker Version: 0.2.1

```
$ NODE_ENV=dev npm i
...
> beaker-plugin-safe-app@0.1.0 build /home/folatt/workspace/MaidSafe/safe_browser-0.2.1/app/node_modules/beaker-plugin-safe-app
> concurrently "npm run build-protocol" "npm run build-api"

[0] 
[0] > beaker-plugin-safe-app@0.1.0 build-protocol /home/folatt/workspace/MaidSafe/safe_browser-0.2.1/app/node_modules/beaker-plugin-safe-app
[0] > cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.protocol.js --progress --profile --colors
[0] 
[1] 
[1] > beaker-plugin-safe-app@0.1.0 build-api /home/folatt/workspace/MaidSafe/safe_browser-0.2.1/app/node_modules/beaker-plugin-safe-app
[1] > cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.api.js --progress --profile --colors
[1] 
[1] module.js:487
[1]     throw err;
[1]     ^
[1] 
[1] Error: Cannot find module '/home/folatt/workspace/MaidSafe/safe_browser-0.2.1/app/node_modules/beaker-plugin-safe-app/webpack.config.api.js'
[1]     at Function.Module._resolveFilename (module.js:485:15)
[1]     at Function.Module._load (module.js:437:25)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at requireConfig (/home/folatt/workspace/MaidSafe/safe_browser-0.2.1/app/node_modules/beaker-plugin-safe-app/node_modules/webpack/bin/convert-argv.js:96:18)
[1]     at /home/folatt/workspace/MaidSafe/safe_browser-0.2.1/app/node_modules/beaker-plugin-safe-app/node_modules/webpack/bin/convert-argv.js:109:17
[1]     at Array.forEach (native)
[1]     at module.exports (/home/folatt/workspace/MaidSafe/safe_browser-0.2.1/app/node_modules/beaker-plugin-safe-app/node_modules/webpack/bin/convert-argv.js:107:15)
[1]     at Object.<anonymous> (/home/folatt/workspace/MaidSafe/safe_browser-0.2.1/app/node_modules/beaker-plugin-safe-app/node_modules/webpack/bin/webpack.js:153:40)
[1]     at Module._compile (module.js:569:30)
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! beaker-plugin-safe-app@0.1.0 build-api: `cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.api.js --progress --profile --colors`
[1] npm ERR! Exit status 1
[1] npm ERR! 
[1] npm ERR! Failed at the beaker-plugin-safe-app@0.1.0 build-api script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1] 
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/folatt/.npm/_logs/2017-07-09T09_26_26_052Z-debug.log
[0] module.js:487
[0]     throw err;
[0]     ^
[0] 
[0] Error: Cannot find module '/home/folatt/workspace/MaidSafe/safe_browser-0.2.1/app/node_modules/beaker-plugin-safe-app/webpack.config.protocol.js'
[0]     at Function.Module._resolveFilename (module.js:485:15)
[0]     at Function.Module._load (module.js:437:25)
[0]     at Module.require (module.js:513:17)
[0]     at require (internal/module.js:11:18)
[0]     at requireConfig (/home/folatt/workspace/MaidSafe/safe_browser-0.2.1/app/node_modules/beaker-plugin-safe-app/node_modules/webpack/bin/convert-argv.js:96:18)
[0]     at /home/folatt/workspace/MaidSafe/safe_browser-0.2.1/app/node_modules/beaker-plugin-safe-app/node_modules/webpack/bin/convert-argv.js:109:17
[0]     at Array.forEach (native)
[0]     at module.exports (/home/folatt/workspace/MaidSafe/safe_browser-0.2.1/app/node_modules/beaker-plugin-safe-app/node_modules/webpack/bin/convert-argv.js:107:15)
[0]     at Object.<anonymous> (/home/folatt/workspace/MaidSafe/safe_browser-0.2.1/app/node_modules/beaker-plugin-safe-app/node_modules/webpack/bin/webpack.js:153:40)
[0]     at Module._compile (module.js:569:30)
[1] npm run build-api exited with code 1
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! beaker-plugin-safe-app@0.1.0 build-protocol: `cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.protocol.js --progress --profile --colors`
[0] npm ERR! Exit status 1
[0] npm ERR! 
[0] npm ERR! Failed at the beaker-plugin-safe-app@0.1.0 build-protocol script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0] 
[0] npm 
[0] ERR! A complete log of this run can be found in:
[0] npm ERR!     /home/folatt/.npm/_logs/2017-07-09T09_26_26_108Z-debug.log
[0] npm run build-protocol exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! beaker-plugin-safe-app@0.1.0 build: `concurrently "npm run build-protocol" "npm run build-api"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the beaker-plugin-safe-app@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/folatt/.npm/_logs/2017-07-09T09_26_26_158Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build-safe-app: `cd ./app/node_modules/beaker-plugin-safe-app && npm i && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build-safe-app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/folatt/.npm/_logs/2017-07-09T09_26_26_201Z-debug.log
```

**Comment by bochaco** [comment]
Hi @Folatt , we are not supporting Arch for the moment, please look at the supported platforms here and the explanation of why: https://safenetforum.org/t/maidsafe-dev-update-july-6-2017/14634

We will eventually try to support more platforms as the community grows.

**Comment by bochaco** [comment]
Hi @Folatt , as said before, we don't support Arch for now, although please give it a try now on latest code from browser's master branch and build it with `NODE_ENV=dev yarn run burnthemall`, you may need to install `yarn` if you don't have it.
