### ISSUE TITLE
Save / read browser state to SAFE not retrieving history

### ISSUE THREAD

**Issue by calumcraig** [maidsafe/safe_browser#859]
**Steps to reproduce:**
Testing on SAFE Browser v0.14-RC1 (Linux but also confirmed on macOS)
1. Launch browser and log into SAFE.
2. Browse some pages and add some bookmarks so there are records for both history and bookmarks:
![Screenshot from 2019-06-21 11-08-20](https://user-images.githubusercontent.com/44327924/59916405-f90bc400-9416-11e9-862c-51c8f71ceeff.png)
3. Select `Save Browser state to SAFE`:
![Screenshot from 2019-06-21 11-08-43](https://user-images.githubusercontent.com/44327924/59916429-088b0d00-9417-11e9-8d0c-8185f634d046.png)
4. Close down browser.
5. Launch a new browser session, log into SAFE.
6. Select `Read Browser state from SAFE`:
![Screenshot from 2019-06-21 11-09-57](https://user-images.githubusercontent.com/44327924/59916485-2eb0ad00-9417-11e9-85b0-fddbc2ed7346.png)

**Expected:**
Both history and bookmarks records will be retrieved and restored.
**Actual:**
Only bookmarks is retrieved - history is not:
![Screenshot from 2019-06-21 11-11-44](https://user-images.githubusercontent.com/44327924/59916536-56a01080-9417-11e9-8092-1e23ddce032d.png)

**Comment by calumcraig** [comment]
Readout from the console while the above process was happening:
```
./safe-browser 
I 19-06-21 11:05:18.042337 Failed to Bootstrap with 138.68.189.17:5483: (ClientNotWhitelisted) Our Client is not whitelisted
I 19-06-21 11:06:24.991779 Bootstrapping(1e0c9d..) Connection failed: The chosen proxy node already has connections to the maximum number of clients allowed per proxy.
I 19-06-21 11:06:24.993043 Bootstrapping(1e0c9d..) Lost connection to proxy PublicId(name: 83157a..).
[main 11:07:58.682] › url must be a string
[main 11:08:58.846] › >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[main 11:08:58.847] › whoops! there was an uncaught error:
[main 11:08:58.847] › {"message":"Cannot read property 'tabs' of undefined","name":"TypeError"}
[main 11:08:58.847] › TypeError: Cannot read property 'tabs' of undefined
    at lastTabIndex (/home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/app/webpack:/app/reducers/windows.ts:119:23)
    at closedWindows (/home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/app/webpack:/app/reducers/windows.ts:171:38)
    at combination (/home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/node_modules/redux/lib/redux.js:451:29)
    at dispatch (/home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/node_modules/redux/lib/redux.js:211:22)
    at /home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/node_modules/electron-redux/dist/middleware/forwardToRenderer.js:33:14
    at /home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/node_modules/redux-thunk/lib/index.js:14:16
    at Object.dispatch (/home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/node_modules/redux-promise/lib/index.js:36:12)
    at EventEmitter.<anonymous> (/home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/node_modules/electron-redux/dist/helpers/replayActionMain.js:23:11)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/electron.asar/browser/api/web-contents.js:346:13) undefined
[main 11:08:58.848] › >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Guest destroy failed: Error: Invalid guestInstanceId: 1
Guest destroy failed: Error: Invalid guestInstanceId: 5
calum@calum-XPS-15-9560:~/Downloads/safe-browser-v0.14-RC1linux-x64$ ./safe-browser 
I 19-06-21 11:09:37.360130 Failed to Bootstrap with 138.68.181.249:5483: (ClientNotWhitelisted) Our Client is not whitelisted
[main 11:10:08.756] › >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[main 11:10:08.758] › whoops! there was an uncaught error:
[main 11:10:08.758] › {"message":"Cannot read property 'tabs' of undefined","name":"TypeError"}
[main 11:10:08.758] › TypeError: Cannot read property 'tabs' of undefined
    at lastTabIndex (/home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/app/webpack:/app/reducers/windows.ts:119:23)
    at closedWindows (/home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/app/webpack:/app/reducers/windows.ts:171:38)
    at combination (/home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/node_modules/redux/lib/redux.js:451:29)
    at dispatch (/home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/node_modules/redux/lib/redux.js:211:22)
    at /home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/node_modules/electron-redux/dist/middleware/forwardToRenderer.js:33:14
    at /home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/node_modules/redux-thunk/lib/index.js:14:16
    at Object.dispatch (/home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/node_modules/redux-promise/lib/index.js:36:12)
    at EventEmitter.<anonymous> (/home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/app.asar/node_modules/electron-redux/dist/helpers/replayActionMain.js:23:11)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/home/calum/Downloads/safe-browser-v0.14-RC1linux-x64/resources/electron.asar/browser/api/web-contents.js:346:13) undefined
[main 11:10:08.758] › >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

**Comment by calumcraig** [comment]
Confirmed that this is no longer happening after the above PR #872 has been merged.

QA verified, moving to done.
